project_name: go-api-simple
release:
  draft: false
  prerelease: auto
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
builds:
  - main: ./pkg/main.go
    binary: go-api-simple
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - app
    replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .FullCommit }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^release'
dockers:
  - dockerfile: Dockerfile.release
    image_templates:
      - "docker.io/krol/go-api-simple:{{ .Version }}"
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.name={{ .ProjectName }}"
      - "--label=org.label-schema.description=Rest Api Golang Sample"
      - "--label=org.label-schema.vendor=Krol"
      - "--label=org.label-schema.version={{ .Version }}"
      - "--label=org.label-schema.build-date={{ .Date }}"
      - "--label=org.label-schema.vcs=https://github.com/krol/go-api-simple"
      - "--label=org.label-schema.vcs-ref={{ .FullCommit }}"
